version: '3.8'

services:
  vpcp-streamlit:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: vpcp-automation-test
    ports:
      - "8501:8501"
    volumes:
      # Mount toàn bộ source code để đồng bộ real-time
      - ./pages:/app/pages
      - ./utils:/app/utils
      - ./prompts:/app/prompts
      - ./original_prompts:/app/original_prompts
      - ./backup_prompts:/app/backup_prompts
      
      # Mount các file Python chính
      - ./site_selector.py:/app/site_selector.py
      - ./original_site.py:/app/original_site.py
      - ./utils.py:/app/utils.py
      - ./general_purpose_agent.py:/app/general_purpose_agent.py
      - ./multi_turn_chat_test.py:/app/multi_turn_chat_test.py
      - ./qa_xlsx_extractor.py:/app/qa_xlsx_extractor.py
      
      # Mount thư mục dữ liệu để lưu kết quả (đồng bộ 2 chiều)
      - ./test_results:/app/test_results
      - ./logs:/app/logs
      - ./scheduled_tests:/app/scheduled_tests
      - ./QAs:/app/QAs
      - ./output:/app/output
      - ./failed_tests:/app/failed_tests
      
      # Mount các file cấu hình và dữ liệu
      - ./requirements.txt:/app/requirements.txt
      - ./.streamlit:/app/.streamlit
      
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - PYTHONPATH=/app
      
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      
    # Giới hạn tài nguyên (optional)
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G 