    [server]
    port = 1234
    address = "0.0.0.0"
    headless = true
    enableCORS = false
    enableXsrfProtection = false

    [browser]
    gatherUsageStats = false
    serverAddress = "localhost"
    serverPort = 1234

    [theme]
    base = "light"
    primaryColor = "#FF4B4B"
    backgroundColor = "#FFFFFF"
    secondaryBackgroundColor = "#F0F2F6"
    textColor = "#262730"

    [runner]
    magicEnabled = true
    installTracer = false
    fixMatplotlib = true

    [client]
    showErrorDetails = true
    toolbarMode = "minimal"